@startuml dataflow

<style>
database {
  LineColor mediumblue
  BackgroundColor aliceblue
}
rectangle {
  LineColor black
  BackgroundColor whitesmoke
}
</style>

!include style.wsd

'#-----------------------------------------------------------------------------#
'# Define components
'#-----------------------------------------------------------------------------#

actor User

rectangle Source

rectangle Sink

package System {
    usecase ETL

    usecase Forward

    database Datastore
}

'#-----------------------------------------------------------------------------#
'# Describe data-flow
'#-----------------------------------------------------------------------------#

Source -> ETL : Raw\nData

ETL -> Datastore : Processed\nData

Datastore -> Forward : Data

Forward -> Sink : Data

User -> ETL : Query
User -> Forward : Query

@enduml
