@startuml entity-relationship
!include style.wsd

'------------------------------------'
' entities
'------------------------------------'

entity entity_1 {
  * entity_1_id: serial4
  --
  attribute_1: float4
  note: varchar(32)
}

entity entity_2 {
  * entity_2_id: serial4
  --
  attribute_2: int8
  note: varchar(32)
}

entity entity_3 {
  * entity_3_id: serial4
  --
  * entity_1_id: int4 <<FK>>
  * entity_2_id: int4 <<FK>>
  attribute_3: float8
}

'------------------------------------'
' relations
'------------------------------------'

entity_1 ||--o{ entity_3
entity_2 ||--o{ entity_3

@enduml
