@startuml sequence

actor User

boundary Interface

User -> Interface : Request
activate Interface

participant Entitiy

Interface -> Entitiy : Message
activate Entitiy

database DB

Entitiy -> DB : SQL
activate DB

DB --> Entitiy : Commit
deactivate DB

Entitiy --> Interface : Return\nvalue
deactivate Entitiy

Interface --> User : Response
deactivate Interface

@enduml
