@startuml

class BTreePCL{
  -root_ : Node_t*
  -kExpectedTreeHeight : size_t
--
.. Utility Functions ..
  -SearchLearfNode() : NodeStack_t
  -SearchLeftmostLeaf() : Node_t *
  -Split() : void
  -Merge() : void
.. APIs ..
  +Read() : payload
  +Scan() : RecordIterator
  +Write() : ReturnCode
  +Insert() : ReturnCode
  +Update() : ReturnCode
  +Delete() : ReturnCode
}

class Node{
  -is_leaf_ : uint16_t
  -record_count_ : uint16_t
  -block_size_ : uint16_t
  -deleted_size_ : uint16_t
  -is_lock_ : mutex
  -next_ : Node_t*
  -high_meta_ : Metadata
  -meta_array_ : Metadata[]
--
.. Getters ..
  +IsRangeInclude() : bool
  +CanMerge() : bool
  +IsLeaf() : bool
  +GetRecordCount() : size_t
  +GetNextNode() : Node_t*
  +GetMetaData() : Metadata
  +GetKey() : key
  +GetHighKey() : key
  +GetPayload() : payload
  +GetRecord() : pair<key, payload>
.. Setters ..
  -SetKey() : void
  -SetPayload() : void
.. Utility Functions ..
  -GetKeyAddr() : void *
  -GetPayloadAddr() : void *
  -IsRightmostOf() : bool
  -SetData() : size_t
  -GetSpaceStatus() : ReturnCode
  -CopyKeyFrom() : size_t
  -CopyHighKeyFrom() : size_t
  -CopyRecordFrom() : void
  -CopyRecordsFrom() : size_t
.. APIs ..
  +SearchRecord() : pair<ReturnCode, size_t>
  +SearchChild() : size_t
  +SearchEndPositionFor() : pair<bool, size_t>
  +Read() : ReturnCode
  +Write() : ReturnCode
  +Insert() : ReturnCode
  +Update() : ReturnCode
  +Delete() : ReturnCode
  +InsertChild() : ReturnCode
  +DeleteChild() : ReturnCode
  +Consolidate() : void
  +Split() : void
  +Merge() : void
}

class Metadata{
  -offset_ : uint32_t
  -key_length_: uint32_t
  -total_length_: uint32_t
--
.. Getters ..
  +GetOffset() : size_t
  +GetKeyLength() : size_t
  +GetTotalLength() : size_t
  +GetPayloadLength() : size_t
.. Setters ..
  +SetOffset() : void
  +SetKeyLength() : void
  +SetTotalLength(): void
}

class RecordIterator{
  -node_ : Node_t*
  -record_count_ : size_t
  -current_pos_ : size_t
  -end_key_ : pair<key, bool>
  -is_end_ : bool
--
.. operators ..
  + *() : pair<key, payload>
  + ++() : void
.. Getters ..
  +HasNext() : bool
  +GetKey() : key
  +GetPayload() : payload
}

BTreePCL "1" -> "1" Node
Node "1" -> "1" Metadata
Node "1" -> "0.." Node
RecordIterator "1" -> "1" Node

@enduml
