name: Ubuntu-20.04

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release
  THREAD_NUM: 2

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        page-size: [1024, 2048, 4096, 8192]
    steps:

    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{secrets.SSH_KEY_FOR_ACTIONS}}
        persist-credentials: false

    - name: Create Build Environment
      shell: bash
      run: |
        sudo apt-get install -y libgflags-dev
        cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ${GITHUB_WORKSPACE} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DB_TREE_PAGE_SIZE=${{matrix.page-size}} -DB_TREE_BUILD_TESTS=ON -DB_TREE_TEST_BUILD_MULTI_THREAD_TESTS=OFF -DB_TREE_TEST_THREAD_NUM=${THREAD_NUM}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel ${THREAD_NUM} --config ${BUILD_TYPE}

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${BUILD_TYPE} --output-on-failure
