name: Unit Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  BUILD_TYPE: Release

jobs:
  unit_test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        page-size: [512, 65536]
        merger-flag: [OFF, ON]

    steps:
    - name: Clone Main Repository
      uses: actions/checkout@v4

    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ${GITHUB_WORKSPACE}
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
        -DB_TREE_BUILD_TESTS=ON
        -DDBGROUP_TEST_EXEC_NUM=30000
        -DDBGROUP_TEST_PAGE_SIZE=${{matrix.page-size}}
        -DDBGROUP_TEST_DISABLE_RECORD_MERGING=${{matrix.merger-flag}}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel --config ${BUILD_TYPE}

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${BUILD_TYPE} --output-on-failure
